//! # Aura Declaration Files (.d.aura)
//!
//! Like TypeScript's .d.ts files — declare types without implementation.
//! Used for package type exports so consumers get type checking
//! without seeing the implementation source.
//!
//! ## Format
//! ```aura
//! // chart.d.aura
//! declare model ChartData
//!   labels: list[text]
//!   values: list[float]
//!
//! declare component Chart(data: ChartData, kind: enum[line, bar, pie])
//!
//! declare fn formatValue(value: float, decimals: int) -> text
//! ```

use crate::ast::*;
use crate::hir::*;
use crate::types::AuraType;

/// Generate a .d.aura declaration file from an HIR module.
/// Strips implementation details, keeps only type signatures.
pub fn generate_declarations(module: &HIRModule) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// {}.d.aura — Type declarations\n",
        module.app.name
    ));
    out.push_str("// Generated by the Aura compiler. Do not edit.\n\n");

    // Models
    for model in &module.models {
        out.push_str(&format!("declare model {}\n", model.name));
        for field in &model.fields {
            out.push_str(&format!(
                "  {}: {}",
                field.name,
                field.field_type.display_name()
            ));
            if let Some(ref default) = field.default {
                out.push_str(" = ...");
            }
            out.push('\n');
        }
        out.push('\n');
    }

    // Components (signature only)
    for comp in &module.components {
        let props: Vec<String> = comp
            .props
            .iter()
            .map(|p| {
                let default = if p.default.is_some() { " = ..." } else { "" };
                format!("{}: {}{}", p.name, p.param_type.display_name(), default)
            })
            .collect();
        if props.is_empty() {
            out.push_str(&format!("declare component {}\n\n", comp.name));
        } else {
            out.push_str(&format!(
                "declare component {}({})\n\n",
                comp.name,
                props.join(", ")
            ));
        }
    }

    // Screens (signature only)
    for screen in &module.screens {
        let params: Vec<String> = screen
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, p.param_type.display_name()))
            .collect();
        if params.is_empty() {
            out.push_str(&format!("declare screen {}\n", screen.name));
        } else {
            out.push_str(&format!(
                "declare screen {}({})\n",
                screen.name,
                params.join(", ")
            ));
        }

        // Export state types
        for state in &screen.state {
            out.push_str(&format!(
                "  state {}: {}\n",
                state.name,
                state.state_type.display_name()
            ));
        }

        // Export action signatures
        for action in &screen.actions {
            let params: Vec<String> = action
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, p.param_type.display_name()))
                .collect();
            if params.is_empty() {
                out.push_str(&format!("  declare action {}\n", action.name));
            } else {
                out.push_str(&format!(
                    "  declare action {}({})\n",
                    action.name,
                    params.join(", ")
                ));
            }
        }

        // Export function signatures
        for func in &screen.functions {
            let params: Vec<String> = func
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, p.param_type.display_name()))
                .collect();
            let ret = func.return_type.display_name();
            if params.is_empty() {
                out.push_str(&format!("  declare fn {} -> {}\n", func.name, ret));
            } else {
                out.push_str(&format!(
                    "  declare fn {}({}) -> {}\n",
                    func.name,
                    params.join(", "),
                    ret
                ));
            }
        }
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_declarations() {
        let source = r#"app Test
  model Todo
    title: text
    done: bool = false
  screen Main
    state todos: list[Todo] = []
    view
      text "hi"
    action addTodo(title: text)
      todos = todos
    fn count -> int
      0"#;
        let result = crate::parser::parse(source);
        let hir = crate::hir::build_hir(result.program.as_ref().unwrap());
        let decl = generate_declarations(&hir);

        assert!(decl.contains("declare model Todo"));
        assert!(decl.contains("title: text"));
        assert!(decl.contains("done: bool"));
        assert!(decl.contains("declare screen Main"));
        assert!(decl.contains("declare action addTodo(title: text)"));
        assert!(decl.contains("declare fn count -> int"));
    }
}
