//! Terminal UI codegen: HIR → ANSI-styled terminal output script.

use aura_core::hir::*;

pub struct TuiOutput {
    /// A self-contained shell script that renders the app in the terminal.
    pub script: String,
    pub filename: String,
}

pub fn compile_to_tui(module: &HIRModule) -> TuiOutput {
    let mut tui = TuiCodegen::new(module);
    tui.generate();
    TuiOutput {
        script: tui.out,
        filename: format!("{}.sh", module.app.name.to_lowercase()),
    }
}

// ANSI escape codes
const RESET: &str = "\\033[0m";
const BOLD: &str = "\\033[1m";
const DIM: &str = "\\033[2m";
const ITALIC: &str = "\\033[3m";
const UNDERLINE: &str = "\\033[4m";
const STRIKE: &str = "\\033[9m";
const RED: &str = "\\033[31m";
const GREEN: &str = "\\033[32m";
const YELLOW: &str = "\\033[33m";
const BLUE: &str = "\\033[34m";
const MAGENTA: &str = "\\033[35m";
const CYAN: &str = "\\033[36m";
const GRAY: &str = "\\033[90m";
const BG_DARK: &str = "\\033[48;5;235m";

struct TuiCodegen<'a> {
    module: &'a HIRModule,
    out: String,
    indent: usize,
}

impl<'a> TuiCodegen<'a> {
    fn new(module: &'a HIRModule) -> Self {
        Self {
            module,
            out: String::new(),
            indent: 0,
        }
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.out.push_str("  ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn generate(&mut self) {
        self.line("#!/bin/bash");
        self.line(&format!(
            "# {} — Generated by Aura Compiler (TUI Backend)",
            self.module.app.name
        ));
        self.line(&format!(
            "# Run: bash {}.sh",
            self.module.app.name.to_lowercase()
        ));
        self.line("");
        self.line("clear");
        self.line("");

        // App header
        self.line(&format!(
            "echo -e \"{}{}  {} {}\"",
            BOLD, MAGENTA, self.module.app.name, RESET
        ));
        self.line(&format!(
            "echo -e \"{}  ─────────────────────────{}\"",
            GRAY, RESET
        ));
        self.line("echo \"\"");

        // Render first screen
        if let Some(screen) = self.module.screens.first() {
            self.emit_view(&screen.view);
        }

        self.line("");
        self.line(&format!(
            "echo -e \"\\n{}  Press any key to exit...{}\"",
            GRAY, RESET
        ));
        self.line("read -n 1 -s");
    }

    fn emit_view(&mut self, view: &HIRView) {
        match view {
            HIRView::Column(layout) => {
                for child in &layout.children {
                    self.emit_view(child);
                }
            }
            HIRView::Row(layout) => {
                // Row: print items on same line
                let mut parts = Vec::new();
                for child in &layout.children {
                    parts.push(self.view_to_inline(child));
                }
                self.line(&format!("echo -e \"  {}\"", parts.join("  ")));
            }
            HIRView::Text(text) => {
                let content = self.expr_to_str(&text.content);
                let style = self.design_to_ansi(&text.design);
                let reset = if style.is_empty() { "" } else { RESET };
                self.line(&format!("echo -e \"  {}{}{}\"", style, content, reset));
            }
            HIRView::Heading(heading) => {
                let content = self.expr_to_str(&heading.content);
                self.line(&format!("echo -e \"  {}{}{}\"", BOLD, content, RESET));
            }
            HIRView::Icon(icon) => {
                let name = self.expr_to_str(&icon.name);
                let emoji = icon_to_emoji(&name);
                self.line(&format!("echo -e \"  {}\"", emoji));
            }
            HIRView::Button(button) => {
                let label = self.expr_to_str(&button.label);
                let color = self.design_color(&button.design);
                self.line(&format!(
                    "echo -e \"  {}{}[ {} ]{}\"",
                    BOLD, color, label, RESET
                ));
            }
            HIRView::TextField(field) => {
                let ph = field.placeholder.as_deref().unwrap_or("...");
                self.line(&format!(
                    "echo -e \"  {}┌────────────────────────┐{}\"",
                    GRAY, RESET
                ));
                self.line(&format!("echo -e \"  {}│ {:<22} │{}\"", GRAY, ph, RESET));
                self.line(&format!(
                    "echo -e \"  {}└────────────────────────┘{}\"",
                    GRAY, RESET
                ));
            }
            HIRView::Checkbox(cb) => {
                self.line(&format!("echo -e \"  [ ] {}\"", cb.binding));
            }
            HIRView::Toggle(toggle) => {
                let label = toggle.label.as_deref().unwrap_or("toggle");
                self.line(&format!("echo -e \"  {}○ {}{}\"", GRAY, label, RESET));
            }
            HIRView::Divider(_) => {
                self.line(&format!(
                    "echo -e \"  {}────────────────────────────{}\"",
                    GRAY, RESET
                ));
            }
            HIRView::Spacer => {
                self.line("echo \"\"");
            }
            HIRView::Badge(badge) => {
                let content = self.expr_to_str(&badge.content);
                self.line(&format!(
                    "echo -e \"  {}{}[{}]{}\"",
                    BOLD, MAGENTA, content, RESET
                ));
            }
            HIRView::Progress(_) => {
                self.line(&format!("echo -e \"  {}▓▓▓▓▓▓▓▓░░░░░░░░{}\"", CYAN, RESET));
            }
            HIRView::Conditional(cond) => {
                self.line("# if condition");
                self.emit_view(&cond.then_view);
            }
            HIRView::Each(each) => {
                self.line(&format!("# each {} in ...", each.item_name));
                self.line(&format!(
                    "echo -e \"  {}(list items would render here){}\"",
                    GRAY, RESET
                ));
            }
            HIRView::ComponentRef(comp_ref) => {
                if let Some(comp) = self
                    .module
                    .components
                    .iter()
                    .find(|c| c.name == comp_ref.name)
                {
                    self.emit_view(&comp.view);
                } else {
                    self.line(&format!("echo \"  [{}]\"", comp_ref.name));
                }
            }
            HIRView::Group(children) => {
                for child in children {
                    self.emit_view(child);
                }
            }
            _ => {
                self.line("# unsupported element");
            }
        }
    }

    fn view_to_inline(&self, view: &HIRView) -> String {
        match view {
            HIRView::Text(text) => {
                let content = self.expr_to_str(&text.content);
                let style = self.design_to_ansi(&text.design);
                if style.is_empty() {
                    content
                } else {
                    format!("{}{}{}", style, content, RESET)
                }
            }
            HIRView::Button(button) => {
                let label = self.expr_to_str(&button.label);
                let color = self.design_color(&button.design);
                format!("{}{}[{}]{}", BOLD, color, label, RESET)
            }
            HIRView::Spacer => "    ".to_string(),
            _ => "...".to_string(),
        }
    }

    fn expr_to_str(&self, expr: &HIRExpr) -> String {
        match expr {
            HIRExpr::StringLit(s) => s.clone(),
            HIRExpr::IntLit(n) => n.to_string(),
            HIRExpr::FloatLit(f) => f.to_string(),
            HIRExpr::BoolLit(b) => b.to_string(),
            HIRExpr::Var(name, _) => format!("{{{}}}", name),
            _ => "...".to_string(),
        }
    }

    fn design_to_ansi(&self, design: &aura_core::design::ResolvedDesign) -> String {
        let mut codes = Vec::new();
        if let Some(ref typo) = design.typography {
            if typo.weight == Some(700) {
                codes.push(BOLD);
            }
            if typo.italic {
                codes.push(ITALIC);
            }
            if typo.underline {
                codes.push(UNDERLINE);
            }
            if typo.strikethrough {
                codes.push(STRIKE);
            }
        }
        if let Some(ref color) = design.color {
            if let Some(ref fg) = color.foreground {
                codes.push(match fg.as_str() {
                    "accent" | "info" => BLUE,
                    "danger" => RED,
                    "warning" => YELLOW,
                    "success" => GREEN,
                    "secondary" | "muted" => GRAY,
                    _ => "",
                });
            }
        }
        codes.retain(|c| !c.is_empty());
        codes.join("")
    }

    fn design_color(&self, design: &aura_core::design::ResolvedDesign) -> &'static str {
        if let Some(ref color) = design.color {
            if let Some(ref fg) = color.foreground {
                return match fg.as_str() {
                    "accent" => MAGENTA,
                    "danger" => RED,
                    "warning" => YELLOW,
                    "success" => GREEN,
                    "info" => CYAN,
                    _ => "",
                };
            }
        }
        MAGENTA
    }
}

fn icon_to_emoji(name: &str) -> &'static str {
    match name {
        "trash" | "trash.fill" => "🗑",
        "plus" | "plus.circle" => "+",
        "star" | "star.fill" => "⭐",
        "heart" => "❤️",
        "checkmark" => "✅",
        "xmark" => "❌",
        "gear" => "⚙️",
        "house" => "🏠",
        "sun.max" => "☀️",
        "cloud" => "☁️",
        "lock" | "lock.circle" => "🔒",
        "camera" => "📷",
        "inbox" => "📥",
        _ => "•",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn compile_source(source: &str) -> TuiOutput {
        let result = aura_core::parser::parse(source);
        assert!(
            result.errors.is_empty(),
            "Parse errors: {:?}",
            result.errors
        );
        let hir = aura_core::hir::build_hir(result.program.as_ref().unwrap());
        compile_to_tui(&hir)
    }

    #[test]
    fn test_tui_minimal() {
        let output =
            compile_source("app Hello\n  screen Main\n    view\n      text \"Hello, Aura!\"");
        assert!(output.script.contains("#!/bin/bash"));
        assert!(output.script.contains("Hello, Aura!"));
        assert!(output.script.contains("Hello"));
    }

    #[test]
    fn test_tui_has_ansi() {
        let output = compile_source(
            "\
app Test
  screen Main
    view
      heading \"Title\"
      text \"subtitle\" .muted",
        );
        assert!(output.script.contains("\\033[1m")); // bold
        assert!(output.script.contains("\\033[0m")); // reset
    }

    #[test]
    fn test_tui_button() {
        let output = compile_source(
            "\
app Test
  screen Main
    view
      button \"Click\" .accent -> test()
    action test
      return",
        );
        assert!(output.script.contains("[ Click ]"));
    }
}
